# Generated by Django 2.1.15 on 2024-07-31 17:23

from django.db import migrations, models
import foro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='carousel_images/', validators=[foro.models.validate_image_dimensions])),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('html_contenido', models.FileField(blank=True, null=True, upload_to='html_files/')),
            ],
        ),
    ]
