# Generated by Django 2.1.15 on 2024-05-01 06:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import foro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[foro.models.unemi_email_validator])),
                ('usuario', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='El nombre de usuario debe tener al menos 3 caracteres'), django.core.validators.MaxLengthValidator(15, message='El nombre de usuario no puede tener más de 15 caracteres')])),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.Usuario'),
        ),
    ]
