# Generated by Django 2.1.15 on 2024-06-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
