# Generated by Django 2.1.15 on 2024-06-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20240612_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
