# Generated by Django 2.1.15 on 2024-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='html_contenido',
            field=models.FileField(blank=True, null=True, upload_to='html_files/'),
        ),
    ]
